language: node_js
dist: trusty
install:
  - npm ci
node_js:
  - 10
deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  app: withmoney
  run:
    - 'npm run sequelize db:seed:undo:all'
    - 'npm run sequelize db:seed:all'
cache:
  directories:
    - ~/.npm
    - ~/.cache
jobs:
  include:
    - stage: unit
      script: npm run unit
      before_script:
        - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
        - "chmod +x ./cc-test-reporter"
        - "./cc-test-reporter before-build"
      after_script:
        - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
    - stage: e2e
      script: npm run e2e
before_script:
  - "cp example.env .env"

