language: node_js
dist: trusty
install:
  - npm install
node_js:
  - "8"
jobs:
  include:
    - stage: unit
      script: npm run unit
    - stage: e2e
      script: npm run e2e
before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
  - "cp example.env .test.env"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
